#ifndef ENGINE_SUBSYSTEM_H
#define ENGINE_SUBSYSTEM_H

namespace Engine
{
    enum EngineSubsystemInitializationResult
    {
        SuccessfullyInitialized,
        FailedToInitialize,
    };

    // Base class for other subsystems that will be generated by the engine.
    // ReSharper disable once CppPolymorphicClassWithNonVirtualPublicDestructor
    class EngineSubsystem
    {
    public:
        virtual EngineSubsystemInitializationResult Initialize();

        // TODO: Consider if we need to provide additional information via return type.
        virtual void Shutdown();
    };
} // namespace Engine

#endif // !ENGINE_SUBSYSTEM_H
